#!/bin/bash -eux

echo "IN THIS SCRIPT, DO WHATEVER IS NEEDED TO SET UP THE WORKER ENVIRONMENT"
echo "THIS FILE IS UNUSED AS THE CONFIGURATION IS COPIED OVER VIA SCP FROM update_submit IN THE SUBMIT_CS CONTAINER"
